---
- name: Deploy PostgreSQL EC2
  hosts: p1db 
  gather_facts: false

  # https://docs.ansible.com/ansible/2.5/modules/docker_container_module.html
  tasks:
  - name: Stop AWS db container
    docker_container:
      name: "p1_aws_db"
      state: stopped
      ignore_errors: yes
  
  - name: Remove AWS db container
    docker_container:
      name: "p1_aws_db"
      state: absent
    
    - name: Run AWS DB container
      docker_container:
        name: "p1_aws_db"
        image: "chamoo334/p1db"
        restart: true
        pull: true
        ports:
        - "5432:5432"