version: '3.7'

services:
  flask-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./src/client
    ports:
      - "5000:5000"
    volumes:
      - ./src/client:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app
    container_name: p1-fa
    command: flask run --host=0.0.0.0
