version: '3.4'

# TODO: volumes
# FIXME: network

# docker network create mynet
# docker run -d -p 5432:5432 --network=mynet --network-alias=testnet flask_server
# docker run -p 5000:5000 --network=mynet --network-alias=testnet flask_client

services:
  wserver:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./src/server
      network:
        devnet
    ports:
      - '5432:5432'
    container_name: where_server

  wclient:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./src/client
      network:
        devnet
    ports:
      - '5000:5000'
    container_name: where_client
    depends_on:
      - wserver

networks:
  devnet: