---
- name: Build Flask Image
  hosts: local
  gather_facts: false
  become: true


  pre_tasks:
  - name: "Make sure remote system is initialized correctly"
    raw: 'ln -s /usr/bin/python3 /usr/bin/python'
    register: set_symlink
    failed_when: set_symlink.rc != 0 and set_symlink.rc != 1

  # https://docs.ansible.com/ansible/2.5/modules/docker_image_module.html
  tasks:
  - name: Build Flask image
    docker_image:
      source: build
      build:
        path: ../src/client
      name: chamoo334/p1fa
      tag: latest
      state: present
      push: yes

  # - name: Run Flask tests




